```{r}
library(tidyverse)
library(DESeq2)
library(SummarizedExperiment)
```

```{r}
rna_dir <- '/Users/henrysanford/Dropbox @RU Dropbox/Vinogradova Laboratory/Exhaustion manuscript/01_RNA-sequencing/PIP5K1-KO/'
fc_output <- paste0(rna_dir, "unnormalized_counts.txt") %>% read_delim(delim = "\t")
sample_info <- paste0(rna_dir, "pip5k1ko_header_info.txt") %>% read_delim()


fc_output %>% pull(Length) -> gene_lengths

fc_output %>%
  column_to_rownames("Geneid") %>% 
  select(-c(Chr, Start, End, Strand, Length)) -> expression_matrix

dds <- DESeqDataSetFromMatrix(countData = expression_matrix,
                                 colData = col_data,
                                 design = ~ Condition)

mcols(dds)$basepairs <- gene_lengths

fpkm_data <- fpkm(dds)

#rld <- rlog(dds, blind = FALSE)
#transformed_data <- assay(rld)

write.table(fpkm_data, paste0(rna_dir, "FPKM_matrix.txt"), sep = "\t", quote = FALSE)


```



```{r}

```



```{r}
counts_table <- paste0(rna_dir, "unnormalized_counts.txt") %>% read_delim(delim = "\t") %>%
  column_to_rownames("Geneid") %>%
  select(-c(Chr, Start, End, Strand, Length))

counts_table %>% colSums()
```


```{r}
rna_dir <- '/Users/henrysanford/Dropbox @RU Dropbox/Vinogradova Laboratory/Exhaustion manuscript/01_RNA-sequencing/PIP5K1-KO/'

counts_table <- paste0(rna_dir, "unnormalized_counts.txt") %>% read_delim() %>%
  column_to_rownames("Geneid") %>%
  select(-c(Chr, Start, End, Strand, Length))

col_data <- paste0(rna_dir, "pip5k1ko_header_info.txt") %>% read_delim()

print(head(counts_table))
print(head(col_data))

dds <- DESeqDataSetFromMatrix(countData = counts_table,
                                 colData = col_data,
                                 design = ~ Condition)

dds <- estimateSizeFactors(dds)

normalized_counts <- counts(dds, normalized=TRUE)

write.table(normalized_counts, file=paste0(rna_dir, "normalized_counts.tsv"), sep="\t", quote=F)

rld <- rlog(dds, blind = FALSE)
transformed_data <- assay(rld)


```

```{r}
write.table(transformed_data, file=paste0(rna_dir, "normalized_counts.tsv"), sep="\t", quote=F)
```


```{r}
pca_data <- plotPCA(rld, intgroup = "Condition", returnData = TRUE)


library(ggrepel)
palette <- c(
  "D8A-Ctrl" = "#603EA6",
  "D8A-1A" = "#5CBED7",
  "D8A-1B" = "#4869B2",
  "D8A-1C" = "#237D41",
  "D8C-Ctrl" = "#E27753",
  "D8C-1A" = "#EC2427",
  "D8C-1B" = "#742D16",
  "D8C-1C" = "#FFCC31"
)

get_condition_name <- function(text) {
  text <- str_split(text, "_sorted") [[1]][1]
  
  l <- str_split(text, "-")
  
  return(paste(c(l[[1]][3], l[[1]][4]), collapse = "-"))
}

pca_data %>%
  mutate(Donor = sub(".*Donor(\\w+)-.*", "\\1", name)) %>%
  mutate(Condition = sapply(name, FUN = get_condition_name)) %>% ggplot(aes(
    x = PC1,
    y = PC2,
    fill = Condition,
    color = Condition,
    shape = Donor
  )) + geom_point(size = 4,
                  stroke = 0.25 / 2,
                  alpha = 0.5) + 
  theme_test() + 
  scale_fill_manual(values = palette) + 
  scale_shape_manual(values = c(21, 22, 23)) + 
  scale_color_manual(values = palette)
```




```{r}
se <- SummarizedExperiment(log2(counts(dds, normalized=TRUE)),
                           colData=colData(dds))

plotPCA( DESeqTransform( se ), intgroup = "Condition" )
```





```{r, fig.width=4, fig.height=2}
plot_loadings <- function(loadings_df, ggplot_obj, arrow_scaling, num_loadings = 5){
  loadings_df %>% arrange(PC1) %>% tail(num_loadings) %>% pull(variable)-> top_pc1
  loadings_df %>% arrange(PC1) %>% head(num_loadings) %>% pull(variable)-> bottom_pc1
  loadings_df %>% arrange(PC2) %>% tail(num_loadings) %>% pull(variable)-> top_pc2
  loadings_df %>% arrange(PC2) %>% head(num_loadings) %>% pull(variable)-> bottom_pc2
  
  loadings_df %>% filter(variable %in% c(top_pc1, bottom_pc1, bottom_pc2, top_pc2)) -> filtered_loadings
  loadings <- ggplot_obj + geom_segment(data= filtered_loadings, 
                      aes(x = 0, y = 0, 
                          xend = PC1 * arrow_scaling, 
                          yend = PC2 * arrow_scaling), 
                      inherit.aes = FALSE,
                    arrow = arrow(length = unit(0.1, "cm")),
                    size = LINE_WIDTH,
                    color="grey90") + 
    geom_text_repel(data= filtered_loadings,
                    mapping = aes(label=variable,x=PC1*arrow_scaling, y=PC2*arrow_scaling), 
                    inherit.aes = FALSE, 
                    segment.size = LINE_WIDTH,
                    min.segment.length = unit(0,"mm"),
                    size=1.763, 
                    color="black",
                    #bg.color = "white",
                    segment.color = "grey") 
  return(loadings)
}

pca_plot <- function(df, loadings_df, x_column, y_column,fn, arrow_scaling = 100){
  
  paste0(pca_dir, "percent_explained.csv") %>% 
  read_csv(show_col_types = FALSE) %>% 
  arrange(principal_component) %>%
  pull(percent_explained) -> percent_explained
  x_lab <- paste0("PC1 (", percent_explained[1], "%)")
  y_lab <- paste0("PC2 (", percent_explained[2], "%)")
  df %>%
    ggplot(aes_string(
      x = x_column,
      y = y_column,
      fill = "Condition",
      color = "Condition",
      shape = "Donor"
    )) + 
    geom_point(size = POINT_SIZE,
             stroke=POINT_STROKE,
             alpha=0.4,
             show.legend = TRUE) + my_theme() +
    theme(legend.key.spacing.y = unit(0, "mm"), aspect.ratio=1) +
    labs(x = x_lab, y = y_lab) + 
    scale_fill_manual(values=palette, name="condition") +
    scale_color_manual(values=palette, name="condition") +
    scale_shape_manual(values = c(21, 22, 23), name = "donor") + 
    guides(fill = guide_legend(ncol = 2), color = guide_legend(ncol =2), shape = guide_legend(ncol = 3)) +
      theme(
    legend.spacing.y = unit(0.1, "cm")  # Reduce space between legends
  )-> plt
  print(plt)
  save_plot(fn, height=2, width = 4)
  
  plot_loadings(loadings_df, plt, arrow_scaling) -> plot_with_loadings
  print(plot_with_loadings)
  save_plot(paste0(fn, "_with_loadings"), height=2, width = 4) 

}

pca_dir <- "/Users/henrysanford/Dropbox @RU Dropbox/Vinogradova Laboratory/Exhaustion manuscript/01_RNA-sequencing/PIP5K1-KO/PCA_5000_genes/"

paste0(pca_dir, 'pca_results.csv') %>%
  read.csv() %>%
  mutate(Donor = sub(".*Donor(\\w+)-.*", "\\1", channel_name)) %>%
  mutate(Condition = sapply(channel_name, FUN = get_condition_name)) -> df


paste0(pca_dir, 'loadings_results.csv') %>%
  read_csv() -> loadings_df
  loadings_df
  
pca_plot(
  df = df,
  loadings_df = loadings_df,
  x_column = "principal.component.1",
  y_column = "principal.component.2",
  fn = '/Users/henrysanford/Dropbox @RU Dropbox/Vinogradova Laboratory/Exhaustion manuscript/01_RNA-sequencing/PIP5K1-KO/PCA_5000_genes/pca',
  arrow_scaling = 20
)
```







```{r}

plot_dir <- '/Users/henrysanford/Dropbox @RU Dropbox/Vinogradova Laboratory/Exhaustion manuscript/01_RNA-sequencing/PIP5K1-KO/PCA_5000_genes/'
clean_term <- function(term) {
  str_split_fixed(term, "_", 2)[2] -> term
  #çgsub("\\b([a-z])", "\\U\\1", tolower(term), perl=TRUE) -> term
  str_replace_all(term, "_", " ") -> term
  str_wrap(term, 40) -> term
  return(term)
}
for (pc in c("PC1", "PC2")) {
  paste0(plot_dir,
         pc,
         "/gseapy.gene_set.prerank.report.csv") %>%
    read_csv(show_col_types = FALSE) %>%
    mutate(
      Term = lapply(Term, FUN = clean_term) %>% unlist(),
      `-log10(FDR)` = -log10(`FDR q-val`)
    ) %>%
    arrange(abs(NES)) -> df
  
  max_score  <- max(df$`-log10(FDR)`[is.finite(df$`-log10(FDR)`)], na.rm = TRUE)
  df$`-log10(FDR)`[is.infinite(df$`-log10(FDR)`)] <- 5.5
  
  # color palette
  df %>%
    filter(`FDR q-val` < 0.05) %>%
    tail(15) %>%
    ggplot(aes(
      x = NES,
      y = reorder(Term, NES),
      fill = `-log10(FDR)`
    )) +
    geom_col(color = "black",
             size = LINE_WIDTH,
             width = 0.5) +
    my_theme() +
    geom_vline(xintercept = 0,
               color = "black",
               size = LINE_WIDTH) +
    labs(x = paste0(pc, " NES"),
         y = NULL,
         fill = expression("-log"[10] * "(FDR)")) +
    theme(
      axis.text.y = element_text(size = 5, family = FONT_FAMILY),
      legend.text = element_text(margin = margin(l = 1)),
      legend.key.height = unit(4, "mm"),
      legend.key.width = unit(4, "mm"),
      panel.grid.major = element_line(color = "grey90", size = LINE_WIDTH),
    ) + 
    scale_fill_continuous(low = "#B3CDE3", high = "#B10F7C") -> plt
  print(plt)
  save_plot(
    paste0(plot_dir, pc, "/top_enriched_sets"),
    width = 4,
    height = 2
  )
}
```


```{r, fig.height=2, fig.width=4}
df <- paste0(rna_dir, 'FPKM_matrix.txt') %>%
  read_delim() %>%
  filter(Geneid %in% c("PIP5K1A", "PIP5K1B", "PIP5K1C"))


df <- df %>%
  pivot_longer(names_to = "sample",
               values_to = "FPKM",
               cols = colnames(df)[colnames(df) != "Geneid"]) %>%
  mutate(Donor = sub(".*Donor(\\w+)-.*", "\\1", sample)) %>%
  mutate(Condition = sapply(sample, FUN = get_condition_name))

df %>%
  ggplot(aes(
    x = Condition,
    shape = Donor,
    fill = Condition,
    y = FPKM,
    color = Condition,
  )) +
  geom_point(size = POINT_SIZE / 2, alpha = 0.5) +
  geom_bar(
    mapping = aes(x = Condition, fill = Condition, y = FPKM, ),
    stat = "summary",
    fun = "mean",
    alpha = 0.5,
    inherit.aes = FALSE,
    show.legend = FALSE,
    color = "black",
    size = POINT_STROKE,
    width = 0.7
  ) +
  facet_wrap( ~ Geneid) +
  my_theme() +
  theme(
    axis.text.x = element_text(angle = 90, size = FONT_SIZE),
    panel.spacing.x = unit(0.5, "mm"),
    strip.background = element_blank(),
    panel.border = element_blank(),
    axis.line.x = AXIS_LINE,
    legend.spacing.y = unit(0, "mm"),
    axis.line.y = AXIS_LINE
  ) +
  scale_fill_manual(values = palette, name = "condition") +
  scale_color_manual(values = palette, name = "condition") +
  scale_shape_manual(values = c(21, 22, 23), name = "donor") + 
  guides(fill = guide_legend(ncol = 2), color = guide_legend(ncol =2), shape = guide_legend(ncol = 3))
```











